### ISSUE TITLE
missing master branch

### ISSUE THREAD

**Issue by Ramblurr** [lethosor/py-df-raws#1]
I'd like to use this library in a python project I'm working on :)

The elusive master branch is missing however, any chance you could push it?

**Comment by lethosor** [comment]
This project is fairly dead, unfortunately, but [PyDwarf](https://github.com/pineapplemachine/PyDwarf) is looking promising - [here](https://github.com/pineapplemachine/PyDwarf/blob/master/scripts/pineapple/pydwarf.deerappear.py) is an example (but there are many other example scripts in that repo as well).

**Comment by Ramblurr** [comment]
Cool, thanks!
